import os
from dataclasses import dataclass, field
from typing import Optional, Union

from dotenv import load_dotenv
from transformers import TrainingArguments
from trl import SFTConfig

from psalm.utils.env_utils import get_env_by_name_or_default, get_list_env_by_name_or_default

load_dotenv()

@dataclass
class TrainerConfig(SFTConfig, TrainingArguments):
    output_dir: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("OUTPUT_DIR", "trainer_outputs", str))
    overwrite_output_dir: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("OVERWRITE_OUTPUT_DIR", False, bool))
    eval_strategy: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("EVAL_STRATEGY", "no", str))
    prediction_loss_only: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("PREDICTION_LOSS_ONLY", False, bool))
    per_device_train_batch_size:  Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("PER_DEVICE_TRAIN_BATCH_SIZE", 8, int))
    per_device_eval_batch_size:  Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("PER_DEVICE_EVAL_BATCH_SIZE", 8, int))
    gradient_accumulation_steps:  Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("GRADIENT_ACCUMULATION_STEPS", 1, int))
    eval_accumulation_steps: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("EVAL_ACCUMULATION_STEPS", None, int))
    eval_delay: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("EVAL_DELAY", None, float))
    torch_empty_cache_steps: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("TORCH_EMPTY_CACHE_STEPS", None, int))
    learning_rate: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("LEARNING_RATE", 5e-5, float))
    weight_decay: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("WEIGHT_DECAY", 0.0, float))
    adam_beta1: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("ADAM_BETA1", 0.9, float))
    adam_beta2: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("ADAM_BETA2", 0.999, float))
    adam_epsilon: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("ADAM_EPSILON", 1e-8, float))
    max_grad_norm: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("MAX_GRAD_NORM", 1.0, float))
    num_train_epochs: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("NUM_TRAIN_EPOCHS", 3.0, float))
    max_steps: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("MAX_STEPS", -1, int))
    lr_scheduler_type: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("LR_SCHEDULER_TYPE", "linear", str))
    warmup_ratio: Optional[float] = field(default_factory=lambda: get_env_by_name_or_default("WARMUP_RATIO", 0.0, float))
    warmup_steps: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("WARMUP_STEPS", 0, int))
    log_level: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("LOG_LEVEL", "passive", str))
    log_level_replica: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("LOG_LEVEL_REPLICA", "warning", str))
    log_on_each_node: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("LOG_ON_EACH_NODE", True, bool))
    logging_dir: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("LOGGING_DIR", None, str))
    logging_strategy: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("LOGGING_STRATEGY", "steps", str))
    logging_first_step: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("LOGGING_FIRST_STEP", False, bool))
    logging_steps: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("LOGGING_STEPS", 500, int))
    logging_nan_inf_filter: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("LOGGING_NAN_INF_FILTER", True, bool))
    save_strategy: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("SAVE_STRATEGY", "steps", str))
    save_steps: Optional[Union[int, float]] = field(default_factory=lambda: get_env_by_name_or_default("SAVE_STEPS", 500, int))
    save_total_limit: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("SAVE_TOTAL_LIMIT", None, int))
    save_safetensors: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("SAVE_SAFETENSORS", False, bool))
    save_on_each_node: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("SAVE_ON_EACH_NODE", True, bool))
    save_only_model: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("SAVE_ONLY_MODEL", False, bool))
    restore_callback_states_from_checkpoint: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("RESTORE_CALLBACK_STATES_FROM_CHECKPOINT", False, bool))
    use_cpu: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("USE_CPU", False, bool))
    seed: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("SEED", 42, int))
    data_seed: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("DATA_SEED", None, int))
    jit_mode_eval: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("JIT_MODE", False, bool))
    use_ipex: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("USE_IPEX", False, bool))
    bf16: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("BF16", False, bool))
    fp16: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("FP16", False, bool))
    fp16_opt_level: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("FP16_OPT_LEVEL", "O1", str))
    fp16_backend: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("FP16_BACKEND", "auto", str))
    half_precision_backend: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("HALF_PRECISION_BACKEND", "auto", str))
    bf16_full_eval: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("BF16_FULL_EVAL", False, bool))
    tf32: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("TF32", False, bool))
    local_rank: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("LOCAL_RANK", -1, int))
    ddp_backend: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("DDP_BACKEND", None, str))
    tpu_num_cores: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("TPU_NUM_CORES", None, int))
    dataloader_drop_last: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("DATALOADER_DROP_LAST", False, bool))
    eval_steps: Optional[Union[int, float]] = field(default_factory=lambda: get_env_by_name_or_default("EVAL_STEPS", None, float))
    dataloader_num_workers: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("DATALOADER_NUM_WORKERS", 0, int))
    run_name: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("RUN_NAME", None, str))
    disable_tqdm: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("DISABLE_TQDM", False, bool))
    remove_unused_columns: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("REMOVE_UNUSED_COLUMNS", False, bool))
    label_names: Optional[list[str]] = field(default_factory=lambda: get_list_env_by_name_or_default("LABEL_NAMES", None))
    load_best_model_at_end: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("LOAD_BEST_MODEL_AT_END", False, bool))
    metric_for_best_model: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("METRIC_FOR_BEST_MODEL", None, str))
    greater_is_better: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("GREATER_IS_BETTER", True, bool))
    ignore_data_skip: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("IGNORE_DATA_SKIP", False, bool))
    deepspeed: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("DEEPSPEED", None, str))
    debug: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("DEBUG", "", str))
    optim: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("OPTIM", "adamw_torch", str))
    optim_args: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("OPTIM_ARGS", None, str))
    report_to: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("REPORT_TO", "all", str))
    dataloader_pin_memory: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("DATALOADER_PIN_MEMORY", True, bool))
    dataloader_persistent_workers: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("DATALOADER_PERSISTENT_WORKERS", False, bool))
    dataloader_prefetch_factor: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("DATALOADER_PREFETCH_FACTOR", None, int))
    push_to_hub: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("PUSH_TO_HUB", False, bool))
    hub_model_id: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("HUB_MODEL_ID", None, str))
    hub_strategy: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("HUB_STRATEGY", "every_save", str))
    hub_token: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("HF_TOKEN", None, str))
    hub_private_repo: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("HUB_PRIVATE_REPO", False, bool))
    hub_always_push_local_checkpoints: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("HUB_ALWAYS_PUSH_LOCAL_CHECKPOINTS", False, bool))
    hub_revision: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("HUB_REVISION", None, str))
    gradient_checkpointing: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("GRADIENT_CHECKPOINTING", False, bool))
    auto_find_batch_size: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("AUTO_FIND_BATCH_SIZE", False, bool))
    full_determinism: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("FULL_DETERMINISM", False, bool))
    eval_on_start: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("EVAL_ON_START", False, bool))
    chat_template_path: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("CHAT_TEMPLATE_PATH", None, str))
    dataset_text_field: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("DATASET_TEXT_FIELD", "text", str))
    dataset_num_proc: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("DATASET_NUM_PROC", None, int))
    eos_token: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("EOS_TOKEN", None, str))
    pad_token: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("PAD_TOKEN", None, int))
    max_length: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("MAX_LENGTH", None, int))
    packing: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("PACKING", False, bool))
    packing_strategy: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("PACKING_STRATEGY", "bfd", str))
    padding_free: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("PADDING_FREE", False, bool))
    pad_to_multiple_of: Optional[int] = field(default_factory=lambda: get_env_by_name_or_default("PAD_TO_MULTIPLE_OF", None, int))
    eval_packing: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("EVAL_PACKING", False, bool))
    completion_only_loss: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("COMPLETION_ONLY_LOSS", False, bool))
    assistant_only_loss: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("ASSISTANT_ONLY_LOSS", False, bool))
    loss_type: Optional[str] = field(default_factory=lambda: get_env_by_name_or_default("LOSS_TYPE", "nll", str))
    activation_offloading: Optional[bool] = field(default_factory=lambda: get_env_by_name_or_default("ACTIVATION_OFFLOADING", False, bool))







